# Generated by Django 3.2.9 on 2021-11-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_shippingaddress_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
