# Generated by Django 3.2.9 on 2021-11-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_inquiry_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry',
            field=models.TextField(max_length=200),
        ),
    ]
