# Generated by Django 3.2.9 on 2021-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_inquiry_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
