# Generated by Django 3.2.9 on 2021-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211128_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='fullname',
            new_name='receiver',
        ),
    ]
