# Generated by Django 3.2.9 on 2021-11-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_fullname_shippingaddress_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phoneNo',
            new_name='contactNo',
        ),
    ]
